version: 3.9

networks:
  web:
    driver: bridge

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  certbot_conf:
  certbot_www:
  certbot_logs:
  fastapi_data:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx
      - nginx_vhost:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  fastapi:
    image: ghcr.io/vstrog/fastapi-hotels:1
    restart: unless-stopped
    volumes:
      - fastapi_/app/data
    environment:
      SQLALCHEMY_DATABASE_URL: sqlite:////app/data/hotels.db
    networks:
      - web
