version: 3.9

services:
  fastapi:
    image: ghcr.io/vstrog/fastapi-hotels:1
    container_name: apihotelssqlite_fastapi_1
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:////app/data/hotels.db
    volumes:
      - ./data:/app/data:Z
    networks:
      - web
    restart: unless-stopped

  nginx:
    image: docker.io/nginx:alpine
    container_name: apihotelssqlite_nginx_1
    depends_on:
      - fastapi
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro,Z
      - ./certbot/conf:/etc/letsencrypt:Z
      - ./certbot/www:/var/www/certbot:Z
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - web
    restart: unless-stopped
    command: >
      /bin/sh -c 'while :; do sleep 6h & wait ${!}; nginx -s reload; done & nginx -g "daemon off;"'

  certbot:
    image: docker.io/certbot/certbot
    container_name: apihotelssqlite_certbot_1
    volumes:
      - ./certbot/conf:/etc/letsencrypt:Z
      - ./certbot/www:/var/www/certbot:Z
    networks:
      - web
    entrypoint: "/bin/sh"
    command: "-c 'trap exit TERM; while :; do sleep 1; done'"

networks:
  web:

      SQLALCHEMY_DATABASE_URL: sqlite:////app/data/hotels.db
    networks:
      - web
